# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iStalk - The art of finding friends' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'GoogleMaps'
pod 'GooglePlaces'
pod 'Firebase'
  # Pods for iStalk - The art of finding friends

end
